### PR TITLE
fix: add helper plugin to keep paths within sandbox

### LINKED ISSUE #58: esbuild leaves the sandbox
Since we turn preserveSymlinks off so that node_modules resolution works with the rules_js symlinks node_modules tree, esbuild will currently leave the sandbox by following symlinks. The rules_js node fs patches don't apply to the golang binary. There is currently no hook in esbuild where we can customize module resolution so that esbuild stays in the bazel sandbox.

If bundling .js files that come from transpiled sources, it is currently recommended to set the following configuration

```
config = {
        "resolveExtensions": [".js"],
    },
```

so that esbuild doesn't pick up and re-transpile the .ts sources it can find outside of the sandbox and seems to prefer (https://github.com/aspect-build/rules_esbuild/pull/57#issuecomment-1209540383).

### PR DESCRIPTION
**Pull request by vpanta**
Fixes #58.

Adds a "bazel-sandbox" helper plugin when using Esbuild under Bazel.

It is on by default but can be opted-out by setting `bazel_sandbox_plugin = False` on an `esbuild` target.

This PR also adds `js_log_level` and `esbuild_log_level` attributes. When `js_log_level` is `debug`, the bazel-sandbox plugin will print out resolution changes it makes.

---

### Type of change

- Bug fix (change which fixes an issue)

**For changes visible to end-users**

- Relevant documentation has been updated
- Suggested release notes are provided below:

Addition of an automatic plugin ensuring esbuild resolution remains within the sandbox.

### Test plan

- Covered by existing test cases
- Manual testing; please provide instructions so we can reproduce:

Manually tested changing log levels and disabling the new plugin by setting `bazel_sandbox_plugin = False`. A follow-up with more testing for this plugin would be good.

### CODE REVIEW

File: helpers/plugins/sandbox.js [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+// Regex matching any non-relative import path
+const pkgImport = /^[^.]/
+
+// Under Bazel, esbuild likes to leave the sandbox, so make sure it
+// stays inside the sandbox by using a separate resolver.
+// https://github.com/aspect-build/rules_esbuild/issues/58
+export function sandboxPlugin() {
+  const bindir = process.env['BAZEL_BINDIR']
+  const sandboxRoot = path.join(process.cwd().split(bindir)[0], bindir)
```
Comment (thesayyn) [inline helpers/plugins/sandbox.js:12]: you can use `process.env.JS_BINARY__EXECROOT`

File: helpers/plugins/sandbox.js [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+        // Prevent us from loading different forms of a module (CJS vs ESM).
+        if (pkgImport.test(importPath)) {
+          if (!moduleCache.has(importPath)) {
+            moduleCache.set(importPath, resolveInSandbox())
+          }
+          return await moduleCache.get(importPath)
+        }
+        return await resolveInSandbox()
+
+        async function resolveInSandbox() {
```
Comment (thesayyn) [inline helpers/plugins/sandbox.js:37]: can you move this function out of this closure and pass everything as an argument?

**Review by thesayyn — DISMISSED** [review]

File: helpers/plugins/sandbox.js (hunk 1 above)
Comment (jbedard) [reply helpers/plugins/sandbox.js:12]: I think you can also move it out of the function and put it alongside `pkgImport`

**Comment by jbedard** [comment]
@thesayyn and I discussed this and overall agree with what you're suggesting. I think this should be setup 100% of the time by the launcher like you said.

In one sense it would be nice to avoid more node since one of the main advantages of esbuild is the use of go, but when we're already launching esbuild from node I don't think this adds any harm (we're not adding another node process being launched etc).

File: helpers/plugins/sandbox.js [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+          }
+        } else {
+          otherOptions.pluginData = {}
+        }
+        otherOptions.pluginData.executedSandboxPlugin = true;
+
+        // Prevent us from loading different forms of a module (CJS vs ESM).
+        if (pkgImport.test(importPath)) {
+          if (!moduleCache.has(importPath)) {
+            moduleCache.set(importPath, resolveInSandbox())
```
Comment (jbedard) [inline helpers/plugins/sandbox.js:31]: Why cache the promise instead of the result?

File: helpers/plugins/sandbox.js [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+          return await moduleCache.get(importPath)
+        }
+        return await resolveInSandbox()
+
+        async function resolveInSandbox() {
+          const result = await build.resolve(importPath, otherOptions)
+
+          // If esbuild attempts to leave the sandbox, map the path back into the sandbox.
+          if (!result.path.startsWith(sandboxRoot)) {
+            const pathPieces = result.path.split(bindir)
```
Comment (jbedard) [inline helpers/plugins/sandbox.js:42]: Can we just use `startsWith`?

File: helpers/plugins/sandbox.js (hunk 3 above)
Comment (jbedard) [reply helpers/plugins/sandbox.js:31]: Or can we avoid the `executedSandboxPlugin` logic by putting the promise into the cache and doing the `moduleCache.has` at the top of the function? 🤔 

```
build.onResolve(... => {
  if (moduleCache.has(importPath)) {
     return await moduleCache.get(importPath)
  }

  const result = resolveInSandbox()
  moduleCache.put(importPath, result)
  return await result
})
```

Comment (vpanta) [reply helpers/plugins/sandbox.js]: > Why cache the promise instead of the result?

So when we first did this, we ran into instability in our bundles from run-to-run without any change in the code. Sometimes the bundle was including the CJS version of a module, sometimes the ESM version, and sometimes both got included. We found that it was actually due to the asynchronous nature of how `esbuild` resolves modules: it would depend on which callsite resolved first and how that callsite was structured. Generally speaking, a `require` call would trigger the CJS version of the module and an `import` would trigger the ESM version of the module.

However, we also realized the logic between `moduleCache.has()` and `moduleCache.get()` needs to be synchronous. This is what was causing the double-module load: one callsite starts processing and `await`s `build.resolve` when `esbuild` starts processing another callsite of a different flavor. We weren't the promise in the cache at that point, so instead the cache gets overloaded and both flavors process separately.

We solved the unstable flavors issue by ensuring all our pre-bundled code was ESM (instead of some CJS some ESM), but we still needed to actually set the promise into the cache to prevent this asynchronous bug.

> Or can we avoid the `executedSandboxPlugin` logic by putting the promise into the cache and doing the `moduleCache.has` at the top of the function? 🤔

Unfortunately no, they serve different purposes. The initial `executedSandboxPlugin` data is to prevent the recursive `build.resolve` call from infinitely recursing, because it triggers another call to the `onResolve` plugin. We want to ensure that second call gets released so it can go through other `onResolve` plugins as needed (`esbuild` stops processing `onResolve` plugins once the first returns data). If we did as you noted, I believe it would deadlock because you'd have a promise `await`ing itself.

Also, we actually only use the `moduleCache` for non-relative imports. For relative imports, we're not concerned about loading different forms of the same module. I will note that I attempted this `onResolve` plugin to filter only non-relative imports but couldn't get it to work right (unfortunately I don't remember the exact issue I ran into, only that I tried it and it failed to work).

File: helpers/plugins/sandbox.js (hunk 1 above)
Comment (vpanta) [reply helpers/plugins/sandbox.js]: Done

**Review by vpanta — COMMENTED** [review]
Thanks for the review. I attempted an initial stab at integrating it with `launcher.js`, but not very sure if I did it in an acceptable way (or fully if it works yet).

I agree that I'd prefer this work within esbuild instead, and while I was hesitant to add a JS resolver call for every single resolution call, having the assurance that it plays better with the sandbox seemed worthwhile.

File: esbuild/private/plugins/sandbox.js [hunk 5]
```diff
@@ -28,29 +29,29 @@ export function sandboxPlugin() {
...
     },
   }
 }
+
+async function resolveInSandbox(build, importPath, otherOptions) {
+  const result = await build.resolve(importPath, otherOptions)
+
+  // If esbuild attempts to leave the sandbox, map the path back into the sandbox.
+  if (!result.path.startsWith(sandboxRoot)) {
+    const pathPieces = result.path.split(bindir)
```
Comment (jbedard) [inline esbuild/private/plugins/sandbox.js:47]: Can we use `startsWith` here as well?

Comment (jbedard) [reply esbuild/private/plugins/sandbox.js:47]: Then `path.join(sandboxRoot, result.slice(bindir.length))` (or something similar)?

**Comment by jbedard** [comment]
@vpanta seeing the sandbox issue again reminded me of this PR... did you have a chance to look at the latest comments or have any other updates?

**Comment by vpanta** [comment]
> @vpanta seeing the sandbox issue again reminded me of this PR... did you have a chance to look at the latest comments or have any other updates?

shoot, sorry, I spaced on this PR. Let me see what I can do with it today.

**Comment by vpanta** [comment]
ugh, sorry again, it's been a crazy time but I am actively working on this PR right now and am hoping to settle it this week.

File: helpers/plugins/sandbox.js (hunk 4 above)
Comment (vpanta) [reply helpers/plugins/sandbox.js]: Done

File: esbuild/private/plugins/sandbox.js (hunk 5 above)
Comment (vpanta) [reply esbuild/private/plugins/sandbox.js]: Done

**Comment by vpanta** [comment]
Ok, the examples are all compiling and I've verified the plugin is being used, so I think this is good for review again.

**Comment by gregmagolan** [comment]
@vpanta I pushed a few changes to get this ready for landing

**Review by gregmagolan — APPROVED** [review]
🚀

**Comment by vpanta** [comment]
Big thanks @gregmagolan to getting this over the line!
